---

- hosts: all
  become: true
  tasks:

  - name: update + remove apache and php packages (Ubuntu)
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: absent
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


  - name: update + remove apache and php packages (CentOS)
    yum:
      name:
        - httpd
        - php
      state: absent
      update_cache: yes
    when: ansible_distribution == "CentOS"
