---

- hosts: all
  become: true
  tasks:

  - name: update repo index (apt)
    apt:
      update_cache: yes
    when: ansible_distribution_file_variety == "Debian"

  - name: remove apache2 package (apt)
    apt:
      name: apache2
      state: absent
    when: ansible_distribution_file_variety == "Debian"

  - name: remove php support for apache (apt)
    apt:
      name: libapache2-mod-php
      state: absent
    when: ansible_distribution_file_variety == "Debian"


  - name: update repo index (dnf)
    dnf:
      update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: remove apache2 package (dnf)
    dnf:
      name: httpd
      state: absent
    when: ansible_distribution == "Fedora"

  - name: remove php support for apache (dnf)
    dnf:
      name: php
      state: absent
    when: ansible_distribution == "Fedora"
