- name: install mariadb package (CentOS)
  tags: db,centos,mariadb
  yum:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"

- name: install mariadb package (Ubuntu)
  tags: db,ubuntu,mariadb-server
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
