- name: install unzip
  package:
    name: unzip

#- name: install terraform
  #unarchive:
    #src: https://releases.hashicorp.com/terraform/1.3.0/terraform_1.3.0_linux_amd64.zip
    #dest: /usr/local/bin
    #remote_src: yes
    #mode: 0755
    #owner: root
    #group: root
